[package]
name = "web-route"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = "1.0.219"
serde_json = "1.0.140"
thiserror = "2.0.12"

[dev-dependencies]
axum = "0.8.4"
axum-test = "17.3.0"
fake = { version = "4.3.0", features = ["derive"] }
serde = { version = "1.0.219", features = ["derive"] }
tokio = { version = "1.45.1", features = ["rt-multi-thread"] }
